<? return array (
  '<FRAMEWORK>' => 
  array (
    'Project' => 'E:\\Dropbox\\Web\\www\\framework\\base\\Project.php',
    'MySQLProvider' => 'E:\\Dropbox\\Web\\www\\framework\\dataprovider\\MySQLProvider.php',
    'IQueriedDataProvider' => 'E:\\Dropbox\\Web\\www\\framework\\dataprovider\\IQueriedDataProvider.php',
    'IQueriedDataTransformer' => 'E:\\Dropbox\\Web\\www\\framework\\dataprovider\\IQueriedDataTransformer.php',
    'Application' => 'E:\\Dropbox\\Web\\www\\framework\\application\\Application.php',
    'BaseSingleton' => 'E:\\Dropbox\\Web\\www\\framework\\base\\BaseSingleton.php',
    'Console' => 'E:\\Dropbox\\Web\\www\\framework\\base\\Console.php',
    'IApplicationEventHandler' => 'E:\\Dropbox\\Web\\www\\framework\\application\\IApplicationEventHandler.php',
    'IEventHandler' => 'E:\\Dropbox\\Web\\www\\framework\\base\\IEventHandler.php',
    'IQueriedDataProviderEventHandler' => 'E:\\Dropbox\\Web\\www\\framework\\dataprovider\\IQueriedDataProviderEventHandler.php',
    'ISessionEventHandler' => '/home/zerinera/test_new_public_html/framework/component/ISessionEventHandler.php',
    'Context' => '/home/zerinera/test_new_public_html/framework/base/Context.php',
    'Model' => 'E:\\Dropbox\\Web\\www\\framework\\model\\Model.php',
    'StorageViewProvider' => '/home/zerinera/test_new_public_html/framework/view/StorageViewProvider.php',
    'ViewProvider' => '/home/zerinera/test_new_public_html/framework/view/ViewProvider.php',
    'IViewProvider' => '/home/zerinera/test_new_public_html/framework/view/IViewProvider.php',
    'XMLFileStorage' => '/home/zerinera/test_new_public_html/framework/storage/XMLFileStorage.php',
    'Storage' => '/home/zerinera/test_new_public_html/framework/storage/Storage.php',
    'IStorage' => '/home/zerinera/test_new_public_html/framework/storage/IStorage.php',
    'IStorageEventHandler' => '/home/zerinera/test_new_public_html/framework/storage/IStorageEventHandler.php',
    'Session' => '/home/zerinera/test_new_public_html/framework/component/Session.php',
    'SQLFilter' => '/home/zerinera/test_new_public_html/framework/dataprovider/SQLFilter.php',
    'IQueryFilter' => '/home/zerinera/test_new_public_html/framework/dataprovider/IQueryFilter.php',
    'LoginModel' => '/home/zerinera/test_new_public_html/framework/component/LoginModel.php',
    'Paginator' => '/home/zerinera/test_new_public_html/framework/pagination/Paginator.php',
    'IPaginator' => '/home/zerinera/test_new_public_html/framework/pagination/IPaginator.php',
    'HTMLView' => 'E:\\Dropbox\\Web\\www\\framework\\view\\HTMLView.php',
    'View' => 'E:\\Dropbox\\Web\\www\\framework\\view\\View.php',
    'WordList' => 'E:\\Dropbox\\Web\\www\\framework\\utility\\WordList.php',
    'SessionStorage' => '/home/zerinera/test_new_public_html/framework/storage/SessionStorage.php',
    'CrossFileStorage' => '/home/zerinera/test_new_public_html/framework/storage/CrossFileStorage.php',
    'PaginatorViewGroup' => '/home/zerinera/test_new_public_html/framework/pagination/PaginatorViewGroup.php',
    'IPaginatorViewGroup' => '/home/zerinera/test_new_public_html/framework/pagination/IPaginatorViewGroup.php',
    'XHRResponder' => 'E:\\Dropbox\\Web\\www\\framework\\responder\\XHRResponder.php',
    'IResponder' => 'E:\\Dropbox\\Web\\www\\framework\\responder\\IResponder.php',
    'JSONFormater' => 'E:\\Dropbox\\Web\\www\\framework\\format\\JSONFormater.php',
    'IOutputFormater' => 'E:\\Dropbox\\Web\\www\\framework\\format\\IOutputFormater.php',
    'ImageProcessor' => '/home/zerinera/test_new_public_html/framework/utility/ImageProcessor.php',
    'Async' => '/home/zerinera/test_new_public_html/framework/async/Async.php',
    'AsyncDelegate' => '/home/zerinera/test_new_public_html/framework/async/AsyncDelegate.php',
    'BaseModel' => '/home/zerinera/test_new_public_html/framework/model/BaseModel.php',
    'CachedResource' => '/home/zerinera/test_new_public_html/framework/model/CachedResource.php',
    'CachedResourceDelegate' => '/home/zerinera/test_new_public_html/framework/model/CachedResourceDelegate.php',
  ),
  'Kolekcionar' => 
  array (
    'IUserModelEventHandler' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/User/IUserModelEventHandler.php',
    'ITransactionModelEventHandler' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/Transaction/ITransactionModelEventHandler.php',
    'IBidModelEventHandler' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/Bid/IBidModelEventHandler.php',
    'IMessageModelEventHandler' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/Message/IMessageModelEventHandler.php',
    'IArticleModelEventHandler' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/Article/IArticleModelEventHandler.php',
    'BidModel' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/Bid/BidModel.php',
    'UserModel' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/User/UserModel.php',
    'UserSession' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/session/UserSession.php',
    'StatsModel' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/Stats/StatsModel.php',
    'BaseLoginModel' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/session/BaseLoginModel.php',
    'TemplateView' => '/home/zerinera/test_new_public_html/kolekcionar/site/public/TemplateView.php',
    'CategoryModel' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/Category/CategoryModel.php',
    'ArticleModel' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/Article/ArticleModel.php',
    'ArticleSearchModel' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/Article/ArticleSearchModel.php',
    'NotificationModel' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/Notifcation/NotificationModel.php',
    'SettingsModel' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/Settings/SettingsModel.php',
    'NavigationModel' => '/home/zerinera/test_new_public_html/kolekcionar/site/public/include/NavigationModel.php',
    'TemplatedPaginatorViewGroup' => '/home/zerinera/test_new_public_html/kolekcionar/adapters/TemplatedPaginatorViewGroup.php',
    'ProjectPaginatorViewGroup' => '/home/zerinera/test_new_public_html/kolekcionar/adapters/ProjectPaginatorViewGroup.php',
    'ArticleResponder' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/Article/ArticleResponder.php',
    'ClientXHRResponder' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/Client/ClientXHRResponder.php',
    'MessageModel' => '/home/zerinera/test_new_public_html/kolekcionar/mvc/Message/MessageModel.php',
  ),
  'Azur Tours B2B - Sunčani odmor' => 
  array (
    'Suncani' => 'E:\\Dropbox\\Web\\www\\azurtours\\suncani-odmor\\model\\Suncani.php',
    'XMLParser' => 'E:\\Dropbox\\Web\\www\\azurtours\\suncani-odmor\\model\\XMLParser.php',
    'HotelModel' => 'E:\\Dropbox\\Web\\www\\azurtours\\suncani-odmor\\model\\HotelModel.php',
    'DestinationModel' => 'E:\\Dropbox\\Web\\www\\azurtours\\suncani-odmor\\model\\DestinationModel.php',
  ),
)?>