<? return array (
  '<FRAMEWORK>' => 
  array (
    'MySQLProvider' => '/public/framework/dataprovider/MySQLProvider.php',
    'IQueriedDataProvider' => '/public/framework/dataprovider/IQueriedDataProvider.php',
    'IQueriedDataTransformer' => '/public/framework/dataprovider/IQueriedDataTransformer.php',
    'Project' => '/public/framework/base/Project.php',
    'Application' => '/public/framework/application/Application.php',
    'BaseSingleton' => '/public/framework/base/BaseSingleton.php',
    'Console' => '/public/framework/base/Console.php',
    'IApplicationEventHandler' => '/public/framework/application/IApplicationEventHandler.php',
    'IEventHandler' => '/public/framework/base/IEventHandler.php',
    'IQueriedDataProviderEventHandler' => '/public/framework/dataprovider/IQueriedDataProviderEventHandler.php',
    'Model' => '/public/framework/model/Model.php',
    'FileStorage' => '/public/framework/storage/FileStorage.php',
    'Storage' => '/public/framework/storage/Storage.php',
    'IStorage' => '/public/framework/storage/IStorage.php',
    'IStorageEventHandler' => '/public/framework/storage/IStorageEventHandler.php',
    'HTMLView' => '/public/framework/view/HTMLView.php',
    'View' => '/public/framework/view/View.php',
    'SQLFilter' => '/public/framework/dataprovider/SQLFilter.php',
    'IQueryFilter' => '/public/framework/dataprovider/IQueryFilter.php',
    'Page' => '/public/framework/base/Page.php',
    'XHRResponder' => '/public/framework/responder/XHRResponder.php',
    'IResponder' => '/public/framework/responder/IResponder.php',
    'JSONFormater' => '/public/framework/format/JSONFormater.php',
    'IOutputFormater' => '/public/framework/format/IOutputFormater.php',
  ),
  'Social Network Publisher Service' => 
  array (
    'URLModel' => '/home/zerinera/socialnetworkpublisher/service/model/url/URLModel.php',
    'URL' => '/home/zerinera/socialnetworkpublisher/service/model/url/URL.php',
    'Entity' => '/home/zerinera/socialnetworkpublisher/service/model/abstract/Entity.php',
    'FacebookModel' => '/home/zerinera/socialnetworkpublisher/service/model/facebook/FacebookModel.php',
    'UserModel' => '/home/zerinera/socialnetworkpublisher/service/model/user/UserModel.php',
    'User' => '/home/zerinera/socialnetworkpublisher/service/model/user/User.php',
    'AccessTokenModel' => '/home/zerinera/socialnetworkpublisher/service/model/acces_token/AccessTokenModel.php',
    'AccessToken' => '/home/zerinera/socialnetworkpublisher/service/model/acces_token/AccessToken.php',
    'PageModel' => '/home/zerinera/socialnetworkpublisher/service/model/page/PageModel.php',
    'FacebookPage' => '/home/zerinera/socialnetworkpublisher/service/model/page/FacebookPage.php',
    'SDKManager' => '/home/zerinera/socialnetworkpublisher/service/model/sdkmanager/SDKManager.php',
    'PostModel' => '/home/zerinera/socialnetworkpublisher/service/model/post/PostModel.php',
    'Post' => '/home/zerinera/socialnetworkpublisher/service/model/post/Post.php',
    'QueueModel' => '/home/zerinera/socialnetworkpublisher/service/model/queue/QueueModel.php',
    'IPostModelEventHandler' => '/home/zerinera/socialnetworkpublisher/service/model/post/IPostModelEventHandler.php',
    'IQueueModelEventHandler' => '/home/zerinera/socialnetworkpublisher/service/model/queue/IQueueModelEventHandler.php',
  ),
)?>