#!/usr/local/bin/php
<?
// create a class in current directory with possible extension

include_once( dirname(__FILE__) . '/../testproject/project.php' );

$call = array_shift( $argv );

list($className, $extensionName) =  explode(':',$argv[0]);

$classFilename = "{$className}.php";

if ( file_exists( $classFilename )  && !in_array('--force' , $argv) ) 
{
	file_put_contents(
		'php://stderr' , "File already exists: $classFilename\n"
	 .	"\t use {$call} {$className}:{$extensionName} --force\n"
	);
}

define ('codeblock',
'{

}');

$tpl = 
'<\?

// AutoGenerated class @ [\'Y-m-d H:i:s\':date]
class [className] $?([extensionName]){extends [extensionName]}
[@codeblock]

\?>'
;


$data = array(
	  'className' => $className
	, 'extensionName' => $extensionName
);

$classCode = produce( $tpl , $data );



file_put_contents( $classFilename , $classCode );


?>