#!/usr/local/bin/php
<?
// create a class in current directory with possible extension

include_once( dirname(__FILE__) . '/../testproject/project.php' );

array_shift( $argv );

list($className, $extensionName) =  explode(':',$argv[0]);

define ('codeblock',
'{

}');

$tpl = 
'<\?

// AutoGenerated class @ [\'Y-m-d H:i:s\':date]
class [className] $?([extensionName]){extends [extensionName]}
[@codeblock]

\?>'
;


$data = array(
	  'className' => $className
	, 'extensionName' => $extensionName
);

$classCode = produce( $tpl , $data );

$classFilename = "{$className}.php";

file_put_contents( $classFilename , $classCode );


?>